#zlab_frontend_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: ZlabFrontendBundle:Default:index }

R_ZlabFrontendBundle_homepage:
    pattern:  /
    defaults: { _controller: ZlabFrontendBundle:Page:index }
    requirements:
        _method:  GET
